# Setup
title:        NSWD
tagline:     Nigel Smith Web Developer
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Nigel Anthony Smith
  url:        https://nigel-smith-developer.co.uk 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
